# Generated by Django 3.1.2 on 2020-10-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatexToHTML', '0002_auto_20201021_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
